GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "userName": "Richard",
    "email": "kodecamp@kodecamp.com",
    "password": "Richard",
    "course": "CS",
    "year": "2016"
}

